### PR TITLE
Enforce strong passwords on password reset form

### PR DESCRIPTION
**Pull request by sbruner**

### CODE REVIEW

**Comment by sbruner** [comment]
To test:
-go to wp-login.php
-click "lost your password"
-once you receive email, click on link.
-You should now be on a form to reset password and confirm it.  This is the form that this pull request enhances.

**Comment by gyrus** [comment]
Thanks, will hopefully have time to test next week.

**Comment by gyrus** [comment]
I think your changes were on the wrong track. The `resetpass_form` action is fired inside the form, presumably to allow extra output in the HTML. How you've used it has no effect at all. I've reverted those changes for now.

The issue seems to be the firing of the `validate_password_reset` hook. This is already hooked into the plugin for validation, but the `$errors` object is just passed - not by reference. So the changes to that object made by the `slt_fsp_validate_strong_password` have no effect. This is unlike the `user_profile_update_errors` action, which passes the `$errors` object by reference.

I'm not sure what to do about this. @simonwheatley do you have any ideas? I guess I didn't test properly when you originally suggested hooking to `validate_password_reset` - it just looked like it was the obvious thing to do, and I didn't notice the lack of ampersand before `$errors`.

**Comment by sbruner** [comment]
Hi Steve

Thanks for the plugin and checking out my pull request. 

I just realized that I wrote this for a multi site install. Maybe that's why it looks like it's not triggering. 

Best,
Steve

Sent from my iPhone
(please excuse the typos)

**Comment by gyrus** [comment]
You mean that's why it looks like it's not triggering for you, or for me? Also, wouldn't the reset password code be the same for single and multi installs? Does anything about multisite installs change the issue I've described regarding `validate_password_reset` not passing `$errors` by reference?

**Comment by sbruner** [comment]
Hi Steve--

Sorry for the late reply.

This works for me on multisite.

Did you try it?

SB

**Comment by gyrus** [comment]
I don't have multisite to test it on. I'll leave it to @boogah the new plugin owner to check out. But I'm still perplexed by the facts in my second comment above! Don't see how the `reset_pass_form` action would do anything if the password validation hook is attached to it, and `$errors` not being passed by reference in `validate_password_reset`.

Or are you saying that the plugin works as-is on multisite, without your changes which I reverted?

**Comment by sbruner** [comment]
I believe it is working with my changes.  I'm not in office so can't double
check right now. Will let you know when I return.

SB


Steve Bruner
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

*SlipFire : *WordPress Development
slipfire.com  |  twitter.com/sbruner
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

*Piklist:* Powerful WordPress Framework
piklist.com  |  twitter.com/piklist
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

**Comment by sbruner** [comment]
I set up a local multisite instance to test this on.

On line 158 your checking ! empty( $errors ) which seems to allows be true.
 $errors seems to always pass an empty object with be trigger this to be
true:

WP_Error Object
(
    [errors:WP_Error:private] => Array
        (
        )

    [error_data:WP_Error:private] => Array
        (
        )

)


When there are actually errors this is what the object looks like:
WP_Error Object
(
    [errors:WP_Error:private] => Array
        (
            [pass] => Array
                (
                    [0] => ERROR: Please make the password a strong one.
                )

        )

    [error_data:WP_Error:private] => Array
        (
        )

)



So the check on line 158 is only really relying on *! $password_ok *to
check for errors. Which actually makes sense.

My function works because $errors is irrelevant.

Does that makes sense?

SB

**Comment by sbruner** [comment]
I just looked at the latest version 1.5, and * ! empty( $errors ) *was
removed, which is what I mentioned in my last email.

Can you include my changes or do you want me to do another pull request?

Thanks
SB


Steve Bruner
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

*SlipFire : *WordPress Development
slipfire.com  |  twitter.com/sbruner
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

*Piklist:* Powerful WordPress Framework
piklist.com  |  twitter.com/piklist
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

**Comment by boogah** [comment]
@sbruner Would you mind doing another pull request so I might have the chance to review it? Thanks!

**Comment by sbruner** [comment]
Done.
https://github.com/boogah/Force-Strong-Passwords/pull/16

Let me know if you have questions.

SB


Steve Bruner
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

*SlipFire : *WordPress Development
slipfire.com  |  twitter.com/sbruner
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

*Piklist:* Powerful WordPress Framework
piklist.com  |  twitter.com/piklist
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

**Pull request merged**
